// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Feedback
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject feedbackMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Feedback";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Rating("Rating"),
		Details("Details"),
		Status("Status"),
		Feedback_Programme("MyFirstModule.Feedback_Programme"),
		Feedback_Account("MyFirstModule.Feedback_Account");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Feedback(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Feedback(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject feedbackMendixObject)
	{
		if (feedbackMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, feedbackMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.feedbackMendixObject = feedbackMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Feedback.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Feedback initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Feedback.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Feedback initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Feedback(context, mendixObject);
	}

	public static myfirstmodule.proxies.Feedback load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Feedback.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Feedback> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Feedback.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Rating
	 */
	public final java.lang.Integer getRating()
	{
		return getRating(getContext());
	}

	/**
	 * @param context
	 * @return value of Rating
	 */
	public final java.lang.Integer getRating(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Rating.toString());
	}

	/**
	 * Set value of Rating
	 * @param rating
	 */
	public final void setRating(java.lang.Integer rating)
	{
		setRating(getContext(), rating);
	}

	/**
	 * Set value of Rating
	 * @param context
	 * @param rating
	 */
	public final void setRating(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer rating)
	{
		getMendixObject().setValue(context, MemberNames.Rating.toString(), rating);
	}

	/**
	 * @return value of Details
	 */
	public final java.lang.String getDetails()
	{
		return getDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of Details
	 */
	public final java.lang.String getDetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Details.toString());
	}

	/**
	 * Set value of Details
	 * @param details
	 */
	public final void setDetails(java.lang.String details)
	{
		setDetails(getContext(), details);
	}

	/**
	 * Set value of Details
	 * @param context
	 * @param details
	 */
	public final void setDetails(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String details)
	{
		getMendixObject().setValue(context, MemberNames.Details.toString(), details);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final myfirstmodule.proxies.ENUM_Status getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final myfirstmodule.proxies.ENUM_Status getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.ENUM_Status.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(myfirstmodule.proxies.ENUM_Status status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.ENUM_Status status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Feedback_Programme
	 */
	public final myfirstmodule.proxies.Programme getFeedback_Programme() throws com.mendix.core.CoreException
	{
		return getFeedback_Programme(getContext());
	}

	/**
	 * @param context
	 * @return value of Feedback_Programme
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Programme getFeedback_Programme(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Programme result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Feedback_Programme.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Programme.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Feedback_Programme
	 * @param feedback_programme
	 */
	public final void setFeedback_Programme(myfirstmodule.proxies.Programme feedback_programme)
	{
		setFeedback_Programme(getContext(), feedback_programme);
	}

	/**
	 * Set value of Feedback_Programme
	 * @param context
	 * @param feedback_programme
	 */
	public final void setFeedback_Programme(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Programme feedback_programme)
	{
		if (feedback_programme == null) {
			getMendixObject().setValue(context, MemberNames.Feedback_Programme.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Feedback_Programme.toString(), feedback_programme.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Feedback_Account
	 */
	public final administration.proxies.Account getFeedback_Account() throws com.mendix.core.CoreException
	{
		return getFeedback_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of Feedback_Account
	 * @throws com.mendix.core.CoreException
	 */
	public final administration.proxies.Account getFeedback_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Feedback_Account.toString());
		if (identifier != null) {
			result = administration.proxies.Account.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Feedback_Account
	 * @param feedback_account
	 */
	public final void setFeedback_Account(administration.proxies.Account feedback_account)
	{
		setFeedback_Account(getContext(), feedback_account);
	}

	/**
	 * Set value of Feedback_Account
	 * @param context
	 * @param feedback_account
	 */
	public final void setFeedback_Account(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account feedback_account)
	{
		if (feedback_account == null) {
			getMendixObject().setValue(context, MemberNames.Feedback_Account.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Feedback_Account.toString(), feedback_account.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return feedbackMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Feedback that = (myfirstmodule.proxies.Feedback) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
