// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Programme
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject programmeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Programme";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Details("Details"),
		ProgramID("ProgramID"),
		StartDate("StartDate"),
		EndDate("EndDate"),
		Mode("Mode"),
		Programme_Location("MyFirstModule.Programme_Location");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Programme(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Programme(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject programmeMendixObject)
	{
		if (programmeMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, programmeMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.programmeMendixObject = programmeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Programme.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Programme initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Programme.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Programme initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Programme(context, mendixObject);
	}

	public static myfirstmodule.proxies.Programme load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Programme.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Programme> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Programme.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Details
	 */
	public final java.lang.String getDetails()
	{
		return getDetails(getContext());
	}

	/**
	 * @param context
	 * @return value of Details
	 */
	public final java.lang.String getDetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Details.toString());
	}

	/**
	 * Set value of Details
	 * @param details
	 */
	public final void setDetails(java.lang.String details)
	{
		setDetails(getContext(), details);
	}

	/**
	 * Set value of Details
	 * @param context
	 * @param details
	 */
	public final void setDetails(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String details)
	{
		getMendixObject().setValue(context, MemberNames.Details.toString(), details);
	}

	/**
	 * @return value of ProgramID
	 */
	public final java.lang.String getProgramID()
	{
		return getProgramID(getContext());
	}

	/**
	 * @param context
	 * @return value of ProgramID
	 */
	public final java.lang.String getProgramID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProgramID.toString());
	}

	/**
	 * Set value of ProgramID
	 * @param programid
	 */
	public final void setProgramID(java.lang.String programid)
	{
		setProgramID(getContext(), programid);
	}

	/**
	 * Set value of ProgramID
	 * @param context
	 * @param programid
	 */
	public final void setProgramID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String programid)
	{
		getMendixObject().setValue(context, MemberNames.ProgramID.toString(), programid);
	}

	/**
	 * @return value of StartDate
	 */
	public final java.util.Date getStartDate()
	{
		return getStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of StartDate
	 */
	public final java.util.Date getStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartDate.toString());
	}

	/**
	 * Set value of StartDate
	 * @param startdate
	 */
	public final void setStartDate(java.util.Date startdate)
	{
		setStartDate(getContext(), startdate);
	}

	/**
	 * Set value of StartDate
	 * @param context
	 * @param startdate
	 */
	public final void setStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date startdate)
	{
		getMendixObject().setValue(context, MemberNames.StartDate.toString(), startdate);
	}

	/**
	 * @return value of EndDate
	 */
	public final java.util.Date getEndDate()
	{
		return getEndDate(getContext());
	}

	/**
	 * @param context
	 * @return value of EndDate
	 */
	public final java.util.Date getEndDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EndDate.toString());
	}

	/**
	 * Set value of EndDate
	 * @param enddate
	 */
	public final void setEndDate(java.util.Date enddate)
	{
		setEndDate(getContext(), enddate);
	}

	/**
	 * Set value of EndDate
	 * @param context
	 * @param enddate
	 */
	public final void setEndDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date enddate)
	{
		getMendixObject().setValue(context, MemberNames.EndDate.toString(), enddate);
	}

	/**
	 * Set value of Mode
	 * @param mode
	 */
	public final myfirstmodule.proxies.ENUM_Mode getMode()
	{
		return getMode(getContext());
	}

	/**
	 * @param context
	 * @return value of Mode
	 */
	public final myfirstmodule.proxies.ENUM_Mode getMode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Mode.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.ENUM_Mode.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Mode
	 * @param mode
	 */
	public final void setMode(myfirstmodule.proxies.ENUM_Mode mode)
	{
		setMode(getContext(), mode);
	}

	/**
	 * Set value of Mode
	 * @param context
	 * @param mode
	 */
	public final void setMode(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.ENUM_Mode mode)
	{
		if (mode != null) {
			getMendixObject().setValue(context, MemberNames.Mode.toString(), mode.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Mode.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Programme_Location
	 */
	public final myfirstmodule.proxies.Location getProgramme_Location() throws com.mendix.core.CoreException
	{
		return getProgramme_Location(getContext());
	}

	/**
	 * @param context
	 * @return value of Programme_Location
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Location getProgramme_Location(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Location result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Programme_Location.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Location.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Programme_Location
	 * @param programme_location
	 */
	public final void setProgramme_Location(myfirstmodule.proxies.Location programme_location)
	{
		setProgramme_Location(getContext(), programme_location);
	}

	/**
	 * Set value of Programme_Location
	 * @param context
	 * @param programme_location
	 */
	public final void setProgramme_Location(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Location programme_location)
	{
		if (programme_location == null) {
			getMendixObject().setValue(context, MemberNames.Programme_Location.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Programme_Location.toString(), programme_location.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return programmeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Programme that = (myfirstmodule.proxies.Programme) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
