// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
function generateRandomString() {

        let length = 4;

        let result = ' ';

        for(let i = 0; i < length; i++) {

            result +=

            String.fromCharCode(65 + Math.floor(Math.random() * 26));

        }

        return result;}
// END EXTRA CODE

/**
 * @returns {Promise.<string>}
 */
export async function JS_GenerateRegID() {
	// BEGIN USER CODE

    const prefix = "ID";

    const date = new Date();



    const month = date.getMonth() + 1; // getMonth() returns month from 0 to 11

    const year = date.getFullYear();



    const str = `${month}-${year}`;



    const randStrSuffix = generateRandomString();

    const randNumSuffix = Math.floor(Math.random()*1000);

    return `${prefix}-${str}-${randStrSuffix}${randNumSuffix}`;

    // throw new Error("JavaScript action was not implemented");

	// END USER CODE
}
